version: '3'
services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: social
      MYSQL_USER: root
      MYSQL_PASSWORD: password
